name: Run Puppeteer Task

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  run-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Puppeteer Chromium
        uses: actions/cache@v3
        with:
          path: ~/.cache/puppeteer
          key: ${{ runner.os }}-puppeteer-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: |
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=false npm install

      - name: Debug Puppeteer executable path
        run: node -e "console.log(require('puppeteer').executablePath())"

      - name: Run scraper
        run: npm run task
        env:
          CHAT_ID: ${{ secrets.CHAT_ID }}
          BOT_API: ${{ secrets.BOT_API }}
